### PR TITLE
Fix static type tests for ancestors of hijacked classes.

### LINKED ISSUE #74: RuntimeTypeTestsTest fails for `java.lang.Number`
https://github.com/tanishiking/scala-wasm/blob/038d769069b4c4d4bfffe8d69550eb44c8f9ef1b/build.sbt#L235-L236

### LINKED ISSUE #84: Primitives are not considered Serializable though they should
https://github.com/tanishiking/scala-wasm/blob/038d769069b4c4d4bfffe8d69550eb44c8f9ef1b/build.sbt#L275-L276

### LINKED ISSUE #92: RegressionTest.eqEqJL{Float,Double} failed: Assertion error
https://github.com/tanishiking/scala-wasm/blob/953adf245065d66c99ee707568a43556b5a57cc8/build.sbt#L248-L249
Follow-up to #87, which moved that test from an "invalid cast" to just those two tests failing.

### PR DESCRIPTION
**Pull request by sjrd**
This commit fixes the result of `x.isInstanceOf[C]` where `x` is a primitive and `C` is an ancestor of the hijacked class for `x`.

For `jl.Number`, which is the only non-`Object` class that is an ancestor of a hijacked class, we add a special case in the codegen.

For interfaces, we add generic code in their `genInstanceTest` function, based on their `specialInstanceTypes`.

This means we have a second place where we need to compute `specialInstanceTypes`. We move it to the preprocessor, and also use it to generically compute `isAncestorOfHijackedClass`. This removes the hard-code set that we had before.

Fix #74.
Fix #84.
Fix #92.

### CODE REVIEW

File: wasm/src/main/scala/ir2wasm/HelperFunctions.scala [hunk 1]
```diff
@@ -1655,8 +1657,40 @@ object HelperFunctions {
       instrs += I32_CONST(1)
       instrs += RETURN
     } // test fail
-    instrs += DROP
-    instrs += I32_CONST(0) // false
+
+    if (classInfo.isAncestorOfHijackedClass) {
+      /* It could be a hijacked class instance that implements this interface.
+       * Test whether `jsValueType(expr)` is in the `specialInstanceTypes` bitset.
+       * In other words, return `(1 << jsValueType(expr)) != 0`.
```
Comment (tanishiking) [inline wasm/src/main/scala/ir2wasm/HelperFunctions.scala:1664]:
```suggestion
       * In other words, return `(1 << jsValueType(expr) & specialInstanceTypes) != 0`.
```

File: wasm/src/main/scala/ir2wasm/HelperFunctions.scala [hunk 2]
```diff
@@ -1655,8 +1657,40 @@ object HelperFunctions {
...
+       */
```
Comment (tanishiking) [inline wasm/src/main/scala/ir2wasm/HelperFunctions.scala:1665]: Though it might be a bit duplicated with an explanation at `specialInstanceTypes`, it would be helpful for me if we can add some example like below here 😅 

```suggestion
       *
       * For example, when the `jsValueType(expr)` is 'string', 'expr.isInstanceOf[j.l.CharSequence]'
       * should be `true` because `j.l.String` implements `j.l.CharSequence`, and
       * `specialInstanceTypes` for `j.l.CharSequence` contains `1 << jsValueType(j.l.String)`.
       */
```

**Review by tanishiking — APPROVED** [review]
I left a minor comment on descriptions, but otherwise LGTM! great work :tada:

File: wasm/src/main/scala/ir2wasm/HelperFunctions.scala (hunk 2 above)
Comment (sjrd) [reply wasm/src/main/scala/ir2wasm/HelperFunctions.scala:1698]: I added a more concrete example. :)
