### PR TITLE
Fix #81: Fix several issues with `@JSExportStatic`.

### LINKED ISSUE #81: Missing initialization of `@JSExportStatic` things
https://github.com/tanishiking/scala-wasm/blob/038d769069b4c4d4bfffe8d69550eb44c8f9ef1b/build.sbt#L261-L262

### PR DESCRIPTION
**Pull request by sjrd**
* Creation and initialization of static fields.
* Call to the class initializer.
* Do not pass `this` as a parameter from the JS bridges, since the Wasm functions do not expect it.

### CODE REVIEW

File: wasm/src/main/scala/ir2wasm/WasmBuilder.scala [hunk 1]
```diff
@@ -797,10 +799,45 @@ class WasmBuilder {
                 instrs += ctx.refFuncWithDeclaration(closureFuncName)
             }
 
-            instrs += CALL(WasmFunctionName.installJSProperty)
+            if (isStatic)
+              instrs += CALL(WasmFunctionName.installJSStaticProperty)
+            else
+              instrs += CALL(WasmFunctionName.installJSProperty)
```
Comment (tanishiking) [inline wasm/src/main/scala/ir2wasm/WasmBuilder.scala:805]: It makes more sense, than passing a flag to JS function :+1:

**Review by tanishiking — APPROVED** [review]
LGTM:tada:
