### PR TITLE
Fix #42 Implement consistent interface table indexing / O(1) type inclusion test for interfaces

### LINKED ISSUE #42: Interface calls are broken.
It turns out the current implementation of interface calls is broken. If I elaborate the `InterfaceCall` test as follows, several problems appear:
```scala
package testsuite.core

import testsuite.Assert.ok

object InterfaceCall {
  def main(): Unit = {
    val c = new Concrete()
    val cAddSub: AddSub = c
    val cZero: Zero = c
    ok(cAddSub.plus(5, 7) == 12)
    ok(cAddSub.minus(5, 7) == -2)
    ok(cZero.zero == 0)
    ok(cAddSub.plus(cZero.zero, 1) == 1 && cAddSub.minus(1, cZero.zero) == 1)

    val o = new OtherConcrete()
    val oAddSub: AddSub = o
    val oZero: Zero = o
    ok(oAddSub.plus(5, 7) == 12)
    ok(oAddSub.minus(5, 7) == -2)
    ok(oZero.zero == 5)
    ok(oAddSub.plus(oZero.zero, 1) == 6 && oAddSub.minus(1, oZero.zero) == -4)
  }

  class Concrete extends AddSub with Zero {
    override def zero: Int = 0
  }

  class OtherConcrete extends Zero with Sub with AddSub {
    override def zero: Int = 5
  }

  trait Adder {
    def plus(a: Int, b: Int) = a + b
  }

  trait Sub {
    def minus(a: Int, b: Int): Int = a - b
  }

  trait AddSub extends Adder with Sub

  trait Zero {
    def zero: Int
  }
}
```
Here I get
```
==> X tests.CoreTests.testsuite.core.InterfaceCall 0.00s scala.scalajs.js.JavaScriptException: CompileError: WebAssembly.instantiate(): struct.new[10] expected type (ref null 79), found ref.func of type (ref 123) @+5866
    at <jscode>.CompileError: WebAssembly.instantiate(): struct.new[10] expected type (ref null 79), found ref.func of type (ref 123) @+5866(Unknown Source)
```
If I uncomment the second half of the test with `OtherConcrete`, the code validates but fails at run-time with:
```
==> X tests.CoreTests.testsuite.core.InterfaceCall 0.00s scala.scalajs.js.JavaScriptException: RuntimeError: illegal cast
    at <jscode>.{anonymous}()@wasm://wasm/04fc619e:wasm-function[125]:0x2e4d(Unknown Source)
    at <jscode>.{anonymous}()@wasm://wasm/04fc619e:wasm-function[124]:0x2dfd(Unknown Source)
    at <jscode>.{anonymous}()@wasm://wasm/04fc619e:wasm-function[239]:0x3d0b(Unknown Source)
```
From a cursory look at our interface dispatch, I think this comes from the fact that we allocate interface indices in the `itable` for each class and interface independently. This means that the table for `Zero` in the itable of `Concrete` is not at the same index as in the itable of `OtherConcrete`. That means either `cZero.zero` or `oZero.zero` must be broken.

We should gather *all* the interfaces of the world and allocate each a distinct index in the itables. That means some entries of the itables will have to be `null`s. It also means they will be super sparse and consume a lot of space, but we can optimize that later (there are many strategies for doing so in the literature). We should get them correct before making them more efficient.

### PR DESCRIPTION
**Pull request by tanishiking**
Fix #42 Implement consistent interface table indexing

This change ensures that the interface tables (itables) array for each class are consistently ordered:
Each interface is assigned a designated index, and its corresponding itable will always be placed at that index in the global itables array.

For example,

```scala
trait A // index = 0
trait B // index = 1

class Foo extends A with B
class Bar extends B with A
```

Both `Foo` and `Bar` will have itables arrays with a length equal to the number of interfaces (A and B in this case).
The itable for `A` will be at index 0, and the itable for `B` will be at index 1, regardless of the order in which the traits are mixed into the class.

---

Also, Optimize type inclusion test for interfaces to O(1) in [172c8af](https://github.com/tanishiking/scala-wasm/pull/50/commits/172c8af2c54a27eb2369e066c8686620a41b2ad2)

Previously, the type inclusion test walking through the interface tables (itables) and returning true if an itable instance was found, resulting in O(N) time complexity.

The optimization leverages the consistent interface table indexing introduced in the previous commit.
Each interface now has a designated index, and its corresponding itable is always placed at that index in the global itables array for all classes that implement that interface.

With this change, the type inclusion test for an interface can be performed by looking up the designated index corresponding to the interface from the class's itables array, and checking if the entry at that index is non-null.
This operation is constant-time, O(1), as it involves a single array lookup and a null check.

For example, the instance test for the `Base1` interface is generated as follows:

```wasm
(func $instanceTest#testsuite.core.Base1__fun (type $fun_type___4___ty)
  (param $expr___local anyref) (result i32)
  (local $local___0___local (ref null $itable___arr))
  block $0 (result (ref null any))
    local.get $expr___local
    br_on_cast_fail $0 (ref null any) (ref $java.lang.Object___struct)
    struct.get $java.lang.Object___struct 1
    local.set $local___0___local
    ref.null any
    local.get $local___0___local
    br_on_null $0
    local.get $local___0___local
    i32.const 5 ;; index of Base1 interface
    array.get $itable___arr
    br_on_null $0
    i32.const 1
    return
  end
  drop
  i32.const 0
)
```

Although this optimization addresses the time complexity concern, the generated itables array is still sparse.
There's a room for further optimizations to compress the itables and reduce memory overhead.

Related https://github.com/tanishiking/scala-wasm/issues/49

### CODE REVIEW

File: wasm/src/main/scala/ir2wasm/HelperFunctions.scala [hunk 1]
```diff
@@ -836,4 +837,70 @@ object HelperFunctions {
...
+    if (!interfaces.isEmpty) {
+
+      // check if itable is already initialized
+      val headIfaceIdx = ctx.getItableIdx(interfaces.head.name)
+      instrs += GLOBAL_GET(
+        WasmImmediate.GlobalIdx(WasmGlobalName.WasmGlobalITableName(className))
+      )
+      instrs += I32_CONST(WasmImmediate.I32(headIfaceIdx))
+      instrs += ARRAY_GET(WasmImmediate.TypeIdx(WasmTypeName.WasmArrayTypeName.itables))
+      instrs += REF_IS_NULL
```
Comment (sjrd) [inline wasm/src/main/scala/ir2wasm/HelperFunctions.scala:865]: This is pretty expensive to do on every object instantiation. Consider moving "Fill in itables" to the `start` function, so that we don't clutter `newDefault` helpers with these tests.

Comment (tanishiking) [reply wasm/src/main/scala/ir2wasm/HelperFunctions.scala:865]: I'm thinking about we can test if the itable is already initialized by checking if the global itable is null, but yeah doing so in `start` function seems even better :+1:

**Comment by tanishiking** [comment]
Also, we should be able to make `isInstanceOf[interface]` O(1) (though this impl generate quite sparse itable arrays)

**Review by sjrd — APPROVED** [review]
Nice :)
