### PR TITLE
Implement `IdentityHashCode` and fix the hashCode of primitives.

### LINKED ISSUE #78: hashCode of floats and doubles is not correct
https://github.com/tanishiking/scala-wasm/blob/038d769069b4c4d4bfffe8d69550eb44c8f9ef1b/build.sbt#L252-L256

### LINKED ISSUE #79: hashCode of bigints and symbols is not correct
https://github.com/tanishiking/scala-wasm/blob/038d769069b4c4d4bfffe8d69550eb44c8f9ef1b/build.sbt#L257-L258

### LINKED ISSUE #80: Various issues with identityHashCode
https://github.com/tanishiking/scala-wasm/blob/038d769069b4c4d4bfffe8d69550eb44c8f9ef1b/build.sbt#L259-L260

Related? #78

### PR DESCRIPTION
**Pull request by sjrd**
Fix #78.
Fix #79.
Fix #80.

### CODE REVIEW

File: wasm/src/main/scala/ir2wasm/HelperFunctions.scala [hunk 1]
```diff
@@ -1349,6 +1350,136 @@ object HelperFunctions {
     fctx.buildAndAddToContext()
   }
 
+  /** `identityHashCode`: `anyref -> i32`.
+    *
+    * This is the implementation of `IdentityHashCode`. It is also used to compute the `hashCode()`
+    * of primitive values when dispatch is required, so it must be consistent with the
```
Comment (tanishiking) [inline wasm/src/main/scala/ir2wasm/HelperFunctions.scala:1356]: What do you mean by `dispatch is required`?
IIUC, this `identityHashCode` is used for the primitive values (other than `long` and `char`
where the receiver (of `hashCode`) type couldn't known as primitive types at compile-time (and caught at these branches https://github.com/tanishiking/scala-wasm/blob/5b184de8ea4e2f69d813614438f12e36f28ddd88/wasm/src/main/scala/ir2wasm/WasmExpressionBuilder.scala#L292-L305 )

Comment (tanishiking) [reply wasm/src/main/scala/ir2wasm/HelperFunctions.scala:1356]: Ah, ok, "dispatch is **not** required" when the `t.receiver.tpe` is known as `PrimType` or a `HIjackedClass` at compile-time, because they will be translated to `ApplyStatically` and we don't need to vtable/itable-dispatch in those cases

**Review by tanishiking — APPROVED** [review]
LGTM!
(I left several comments, but I think I could make sense on my own)

**Comment by sjrd** [comment]
I added comments to embed your notes in the code.
